const fs = require('fs');

const filePath = 'src/app/contrl-panl/page.tsx';
const content = fs.readFileSync(filePath, 'utf8');
const lines = content.split('\n');

// Lines are 1-indexed in the viewer but 0-indexed in the array
// We need to replace lines 167-199 (1-indexed) → indices 166-198
// Line 167 is "export default function ControlPanelPage() {"
// Line 199 is the closing "    }" of the if(!authRole) block
// Line 200 is empty line before /* ── DASHBOARD SCREEN ── */

const startIdx = 166; // line 167 (0-indexed)
const endIdx   = 199; // line 200 (exclusive) — keep from line 201 onward

const newLines = [
`/* ═════════════════  COMPONENT  ═════════════════ */`,
`export default function ControlPanelPage() {`,
`    const ADMIN_ROLES = ['superadmin', 'masteradmin', 'instadmin', 'deptadmin'];`,
`    const [authRole, setAuthRole] = useState<string | null>(null);`,
`    const [authLabel, setAuthLabel] = useState('');`,
`    const [email, setEmail] = useState('');`,
`    const [password, setPassword] = useState('');`,
`    const [showPw, setShowPw] = useState(false);`,
`    const [error, setError] = useState('');`,
`    const [isLoggingIn, setIsLoggingIn] = useState(false);`,
`    const [isSidebarOpen, setIsSidebarOpen] = useState(false);`,
`    const [activeSectionKey, setActiveSectionKey] = useState<SectionKey | null>(null);`,
``,
`    const getLabel = (role: string): string => ({`,
`        superadmin: 'Super Admin',`,
`        masteradmin: 'Master Admin',`,
`        instadmin: 'Institution Admin',`,
`        deptadmin: 'Department Admin',`,
`    } as Record<string,string>)[role] ?? role;`,
``,
`    /* On mount: if valid admin cookie already exists, skip login form */`,
`    useEffect(() => {`,
`        const match = document.cookie.match(/(^| )role=([^;]+)/);`,
`        if (match && match[2] && ADMIN_ROLES.includes(match[2])) {`,
`            setAuthRole(match[2]);`,
`            setAuthLabel(getLabel(match[2]));`,
`        }`,
`        // No cookie → stay on login form; do NOT redirect to /login`,
`    }, []);`,
``,
`    const handleLogin = async (e: React.FormEvent) => {`,
`        e.preventDefault();`,
`        setError('');`,
`        setIsLoggingIn(true);`,
`        try {`,
`            const res = await fetch('/api/auth/login', {`,
`                method: 'POST',`,
`                headers: { 'Content-Type': 'application/json' },`,
`                body: JSON.stringify({ email: email.trim(), password }),`,
`            });`,
`            const data = await res.json();`,
`            if (!res.ok || !data.success) {`,
`                setError(data.error || 'Login failed. Please check your credentials.');`,
`                return;`,
`            }`,
`            const roleMatch = document.cookie.match(/(^| )role=([^;]+)/);`,
`            const cookieRole = roleMatch?.[2] ?? '';`,
`            if (!ADMIN_ROLES.includes(cookieRole)) {`,
`                setError('Access denied. This panel requires administrator privileges.');`,
`                document.cookie = 'role=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/';`,
`                return;`,
`            }`,
`            setAuthRole(cookieRole);`,
`            setAuthLabel(getLabel(cookieRole));`,
`        } catch {`,
`            setError('Network error. Please try again.');`,
`        } finally {`,
`            setIsLoggingIn(false);`,
`        }`,
`    };`,
``,
`    const handleLogout = () => {`,
`        document.cookie = 'role=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/';`,
`        setAuthRole(null);`,
`        setAuthLabel('');`,
`        setEmail('');`,
`        setPassword('');`,
`    };`,
``,
`    /* ── LOGIN SCREEN ── */`,
`    if (!authRole) {`,
`        return (`,
`            <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-emerald-50 flex items-center justify-center p-4">`,
`                <div className="absolute inset-0 overflow-hidden pointer-events-none">`,
`                    <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-emerald-200/40 rounded-full blur-3xl" />`,
`                    <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-purple-200/30 rounded-full blur-3xl" />`,
`                </div>`,
`                <div className="relative w-full max-w-md">`,
`                    <div className="text-center mb-10">`,
`                        <div className="flex justify-center mb-5">`,
`                            <MededuLogo size={64} className="shadow-xl shadow-emerald-600/20" />`,
`                        </div>`,
`                        <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">Control Panel</h1>`,
`                        <p className="text-slate-500 mt-2 text-sm">MedEduAI · Restricted Access</p>`,
`                    </div>`,
`                    <form onSubmit={handleLogin} className="bg-white border border-slate-200 rounded-3xl p-8 shadow-xl shadow-slate-200/50">`,
`                        <div className="flex items-center gap-3 mb-8">`,
`                            <div className="w-10 h-10 bg-emerald-50 rounded-xl flex items-center justify-center border border-emerald-100">`,
`                                <Lock className="w-5 h-5 text-emerald-600" />`,
`                            </div>`,
`                            <div>`,
`                                <h2 className="text-lg font-bold text-slate-900">Administrator Sign In</h2>`,
`                                <p className="text-xs text-slate-500">Enter your admin credentials to continue</p>`,
`                            </div>`,
`                        </div>`,
`                        {error && (`,
`                            <div className="mb-6 px-4 py-3 rounded-xl bg-red-50 border border-red-200 text-red-600 text-sm font-medium flex items-center gap-2">`,
`                                <AlertCircle className="w-4 h-4 flex-shrink-0" />`,
`                                {error}`,
`                            </div>`,
`                        )}`,
`                        <div className="space-y-5">`,
`                            <div>`,
`                                <label className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-2 block">Email</label>`,
`                                <input`,
`                                    id="cp-email"`,
`                                    type="email"`,
`                                    autoComplete="email"`,
`                                    required`,
`                                    value={email}`,
`                                    onChange={(e) => setEmail(e.target.value)}`,
`                                    className="w-full px-4 py-3 rounded-xl bg-slate-50 border border-slate-200 text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-emerald-500/30 focus:border-emerald-400 transition-all text-sm"`,
`                                    placeholder="admin@mededuai.com"`,
`                                />`,
`                            </div>`,
`                            <div>`,
`                                <label className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-2 block">Password</label>`,
`                                <div className="relative">`,
`                                    <input`,
`                                        id="cp-password"`,
`                                        type={showPw ? 'text' : 'password'}`,
`                                        autoComplete="current-password"`,
`                                        required`,
`                                        value={password}`,
`                                        onChange={(e) => setPassword(e.target.value)}`,
`                                        className="w-full px-4 py-3 rounded-xl bg-slate-50 border border-slate-200 text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-emerald-500/30 focus:border-emerald-400 transition-all text-sm pr-12"`,
`                                        placeholder="••••••••••"`,
`                                    />`,
`                                    <button type="button" onClick={() => setShowPw(!showPw)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600 transition-colors">`,
`                                        {showPw ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}`,
`                                    </button>`,
`                                </div>`,
`                            </div>`,
`                        </div>`,
`                        <button`,
`                            id="cp-login-btn"`,
`                            type="submit"`,
`                            disabled={isLoggingIn}`,
`                            className="w-full mt-8 py-3.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 shadow-lg shadow-emerald-600/20"`,
`                        >`,
`                            {isLoggingIn ? (`,
`                                <><span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Authenticating…</>`,
`                            ) : (`,
`                                <><Shield className="w-5 h-5" /> Access Control Panel</>`,
`                            )}`,
`                        </button>`,
`                    </form>`,
`                    <p className="text-center text-slate-400 text-xs mt-8">© 2026 MedEduAI · All rights reserved</p>`,
`                </div>`,
`            </div>`,
`        );`,
`    }`,
``
];

// Verify the start line looks correct
console.log('Line at startIdx (should be component marker):', lines[startIdx - 1]);
console.log('Line at endIdx (should be empty before DASHBOARD comment):', lines[endIdx]);

const before = lines.slice(0, startIdx - 1);     // everything before line 167
const after  = lines.slice(endIdx);               // from line 201 onward

const result = [...before, ...newLines, ...after].join('\n');
fs.writeFileSync(filePath, result, 'utf8');
console.log('Done! Total lines now:', result.split('\n').length);
