-- ==========================================
-- MedEduAI Supabase Initial Schema
-- PostgreSQL with Row Level Security (RLS)
-- ==========================================

-- EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ENUMS
CREATE TYPE user_role AS ENUM ('student', 'teacher', 'admin');

-- 1. USERS
CREATE TABLE users (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    role user_role DEFAULT 'student',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. COURSES
CREATE TABLE courses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. SUBJECTS
CREATE TABLE subjects (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    course_id UUID REFERENCES courses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. TOPICS
CREATE TABLE topics (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    subject_id UUID REFERENCES subjects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. LMS CONTENT (Generated by AI)
CREATE TABLE lms_content (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    topic_id UUID REFERENCES topics(id) ON DELETE CASCADE,
    introduction TEXT,
    detailed_notes TEXT,
    summary TEXT,
    flashcards JSONB,
    ppt_content JSONB,
    last_generated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. ASSESSMENTS / QUESTION BANK
CREATE TABLE assessments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    topic_id UUID REFERENCES topics(id) ON DELETE CASCADE,
    marks INT NOT NULL, -- 1, 2, 3, 5, 10
    question_text TEXT NOT NULL,
    question_type TEXT, -- e.g. "mcq", "case-based", "reasoning", "essay"
    options JSONB, -- For MCQs
    correct_answer TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. ATTENDANCE (Teacher Module)
CREATE TABLE attendance (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    course_id UUID REFERENCES courses(id),
    teacher_id UUID REFERENCES users(id),
    student_id UUID REFERENCES users(id),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'present', -- 'present', 'absent'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(course_id, student_id, date)
);

-- 8. EVALUATION EMS / RUBRICS
CREATE TABLE examinations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    teacher_id UUID REFERENCES users(id),
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE exam_questions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    exam_id UUID REFERENCES examinations(id) ON DELETE CASCADE,
    question_number INT NOT NULL,
    question_text TEXT NOT NULL,
    marks INT NOT NULL,
    question_type TEXT,
    ai_rubric JSONB,
    is_rubric_approved BOOLEAN DEFAULT FALSE
);

CREATE TABLE student_scripts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    exam_id UUID REFERENCES examinations(id) ON DELETE CASCADE,
    student_name TEXT NOT NULL,
    roll_no TEXT NOT NULL,
    total_marks INT DEFAULT 0,
    status TEXT DEFAULT 'pending', -- pending, evaluating, evaluated, approved
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE script_answers (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    script_id UUID REFERENCES student_scripts(id) ON DELETE CASCADE,
    exam_question_id UUID REFERENCES exam_questions(id),
    image_url TEXT,
    extracted_text TEXT,
    ai_marks INT,
    ai_justification TEXT,
    ai_missing_keywords JSONB,
    teacher_override_marks INT
);

-- 9. AI LOGS
CREATE TABLE ai_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    module TEXT NOT NULL,
    prompt TEXT,
    response TEXT,
    tokens_used INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 10. USAGE LIMITS
CREATE TABLE usage_limits (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES users(id) UNIQUE,
    mentor_questions_today INT DEFAULT 0,
    last_reset_date DATE DEFAULT CURRENT_DATE,
    plan_type TEXT DEFAULT 'free', -- free, premium
    trial_start_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==========================================
-- ROW LEVEL SECURITY POLICIES
-- ==========================================

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE lms_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE examinations ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_scripts ENABLE ROW LEVEL SECURITY;
ALTER TABLE script_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_limits ENABLE ROW LEVEL SECURITY;

-- Admins can do anything
CREATE POLICY admin_all ON users FOR ALL USING ((SELECT role FROM users WHERE id = auth.uid()) = 'admin');

-- Users can read all courses, subjects, topics, lms, and assessments
CREATE POLICY read_courses ON courses FOR SELECT USING (true);
CREATE POLICY read_subjects ON subjects FOR SELECT USING (true);
CREATE POLICY read_topics ON topics FOR SELECT USING (true);
CREATE POLICY read_lms ON lms_content FOR SELECT USING (true);
CREATE POLICY read_assessments ON assessments FOR SELECT USING (true);

-- Teachers can write courses, subjects, topics, lms, and assessments
CREATE POLICY teacher_write_courses ON courses FOR ALL USING ((SELECT role FROM users WHERE id = auth.uid()) IN ('teacher', 'admin'));
CREATE POLICY teacher_write_subjects ON subjects FOR ALL USING ((SELECT role FROM users WHERE id = auth.uid()) IN ('teacher', 'admin'));
CREATE POLICY teacher_write_topics ON topics FOR ALL USING ((SELECT role FROM users WHERE id = auth.uid()) IN ('teacher', 'admin'));
CREATE POLICY teacher_write_lms ON lms_content FOR ALL USING ((SELECT role FROM users WHERE id = auth.uid()) IN ('teacher', 'admin'));
CREATE POLICY teacher_write_assessments ON assessments FOR ALL USING ((SELECT role FROM users WHERE id = auth.uid()) IN ('teacher', 'admin'));

-- Teachers can manage attendance
CREATE POLICY teacher_attendance ON attendance FOR ALL USING ((SELECT role FROM users WHERE id = auth.uid()) IN ('teacher', 'admin'));
-- Students can only read their own attendance
CREATE POLICY student_attendance ON attendance FOR SELECT USING (student_id = auth.uid());

-- Teachers can manage their own examinations
CREATE POLICY teacher_manage_exams ON examinations FOR ALL USING (teacher_id = auth.uid() OR (SELECT role FROM users WHERE id = auth.uid()) = 'admin');
CREATE POLICY teacher_manage_exam_q ON exam_questions FOR ALL USING (true); -- Ideally join to exams, but kept simple for AI
CREATE POLICY teacher_manage_scripts ON student_scripts FOR ALL USING (true);
CREATE POLICY teacher_manage_answers ON script_answers FOR ALL USING (true);

-- Anyone can read their own usage limits
CREATE POLICY own_usage_limits ON usage_limits FOR SELECT USING (user_id = auth.uid());

-- Triggers to reset 'mentor_questions_today' when 'last_reset_date' is old could be added here.
